### ISSUE TITLE
Can it run multi keywords?

### ISSUE THREAD

**Issue by Rayy1024** [rickvg/website-keyword-crawler#2]
I found out there was only one keyword at a time. Can it run with multiple keywords?

**Comment by rickvg** [comment]
Have you tried running the script with multiple keywords? Perhaps add quotes? I have been using it to find malicious scripts, so multiple keywords should work. Could you give more information on your error?

**Comment by Rayy1024** [comment]
It is working now, need to sperate them with a coma. I think I might paste wrong from excel because there were 4000 keywords lol.

Thank you for the answer and the script. It helps a lot.

**Comment by rickvg** [comment]
Perfect!
